### ISSUE TITLE
controller error on "deis pull" if image already associated with previous release

### ISSUE THREAD

**Issue by seanknox** [deis/controller#1020]
Setup info:
- workflow v2.4.1
- using an external registry (quay.io)

```
$ deis releases -a acceptance
v45	2016-08-28T22:23:19Z	admin deployed quay.io/my_repo/able_rails:16019582573fe2f2f51b0a293de1d19a922afbbf
v44	2016-08-28T20:27:08Z	ci deployed quay.io/my_repo/able_rails:4d5244329212e570fd19ecf0d910b9bac5d9072c
v43	2016-08-28T06:15:31Z	ci deployed quay.io/my_repo/able_rails:16019582573fe2f2f51b0a293de1d19a922afbbf
...
```

STR:
1. deploy `able_rails:16019582573fe2f2f51b0a293de1d19a922afbbf` image from external registry using `deis pull`
2. deploy a newer `able_rails:4d5244329212e570fd19ecf0d910b9bac5d9072c` image using `deis pull`
3. deploy same image from step 1 using `deis pull`
4. after getting `Creating build... Error: Unknown Error (400): {"detail":"(app::deploy): ('failed to update Service \"acceptance\" in Namespace \"acceptance\": 409 Conflict', 'acceptance', 'acceptance')"}`, I tried again

As a result, the app was scaled down to no processes:
```
INFO [acceptance]: Deployment acceptance-worker with release v45 already exists. Stopping deploy
INFO [acceptance]: Deployment acceptance-cron with release v45 already exists. Stopping deploy
INFO [acceptance]: Deployment acceptance-web with release v45 already exists. Stopping deploy
acceptance-web-1647476401-mzrld -- shutting down, got signal: Terminated
acceptance-web-1647476401-pfdwa -- shutting down, got signal: Terminated
acceptance-worker-1374294020-rkxl5 -- shutting down, got signal: Terminated
``` 

And I was unable to scale them back up normally:
```
[seanknox:...ucture/us-east-1/nonphi/k8s]$ deis ps:scale web=1 worker=1 cron=0 -a acceptance                                (master✱)
Scaling processes... but first, coffee!
Error: Not Found
```

I rolled back a release and was then able to scale processes back up.

Full controller error below:

```
INFO [acceptance]: admin deployed quay.io/my_repo/able_rails:16019582573fe2f2f51b0a293de1d19a922afbbf
INFO [acceptance]: quay.io/my_repo/able_rails:16019582573fe2f2f51b0a293de1d19a922afbbf exists in the target registry. Using image for release 45 of app acceptance
ERROR [acceptance]: (app::deploy): ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')
ERROR:root:(app::deploy): ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')
Traceback (most recent call last):
  File "/app/scheduler/__init__.py", line 216, in _update_application_service
    self.update_service(namespace, namespace, data=service)
  File "/app/scheduler/__init__.py", line 1229, in update_service
    'update Service "{}" in Namespace "{}"', namespace, name
scheduler.KubeHTTPException: ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/models/app.py", line 562, in deploy
    async_run(tasks)
  File "/app/api/utils.py", line 169, in async_run
    raise error
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/app/api/utils.py", line 182, in async_task
    yield from loop.run_in_executor(None, params)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/scheduler/__init__.py", line 148, in deploy
    self._update_application_service(namespace, name, app_type, port, routable, service_annotations)  # noqa
  File "/app/scheduler/__init__.py", line 219, in _update_application_service
    self.update_service(namespace, namespace, data=old_service)
  File "/app/scheduler/__init__.py", line 1229, in update_service
    'update Service "{}" in Namespace "{}"', namespace, name
scheduler.KubeHTTPException: ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 566, in deploy
    raise ServiceUnavailable(err) from e
api.exceptions.ServiceUnavailable: (app::deploy): ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 181, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 258, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: (app::deploy): ('failed to update Service "acceptance" in Namespace "acceptance": 409 Conflict', 'acceptance', 'acceptance')
```

**Comment by helgi** [comment]
I believe you are hitting the bug that https://github.com/deis/controller/pull/1003 solved (currently in master only, will ship with the next release)

**Comment by seanknox** [comment]
@helgi right you were! I applied controller v2.4.2 and deploys are working without downtime. Though I'm (still) seeing pods from previous releases spun up erroneously, more info at https://github.com/deis/controller/issues/989.

**Comment by seanknox** [comment]
thanks again!
