### ISSUE TITLE
UnboundLocalError scaling non-web process

### ISSUE THREAD

**Issue by mboersma** [deis/controller#1021]
Pushing an app with Deis Workflow v2.4.1 with a non-web ("monitor") process caused this stack trace:
```python
ERROR:root:local variable 'kwargs' referenced before assignment
Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 570, in deploy
    self.verify_application_health(**kwargs)
UnboundLocalError: local variable 'kwargs' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 474, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 480, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: local variable 'kwargs' referenced before assignment
```
The first trace is the salient one.

**Comment by kmala** [comment]
https://github.com/deis/controller/pull/1003 fixes this issue.
