### ISSUE TITLE
RC based application upgrading to Deployment v2.5

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#1054]
When attempting to update an application previously deployed with Deis v2.3 the following error occurs on v2.5.

```10.245.52.137 "POST /v2/hooks/config/ HTTP/1.1" 200 223 "deis-builder"
INFO [devdash]: build devdash-f200e0a created
INFO [devdash]: jenkins deployed 03ebad5
INFO [devdash]: buildpack type detected. Defaulting to $PORT 5000
INFO [devdash]: adding 30s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
INFO [devdash]: This deployments overall timeout is 150s - batch timout is 150s and there are 1 batches to deploy with a total of 1 pods
INFO [devdash]: waited 10s and 1 pods are in service
INFO [devdash]: waited 20s and 1 pods are in service
INFO [devdash]: waited 30s and 1 pods are in service
ERROR:root:'KubeHTTPClient' object has no attribute '_scale_rc'
Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 612, in deploy
    release.cleanup_old()
  File "/app/api/models/release.py", line 273, in cleanup_old
    self._delete_release_in_scheduler(self.app.id, version)
  File "/app/api/models/release.py", line 353, in _delete_release_in_scheduler
    self._scheduler._scale_rc(namespace, controller['metadata']['name'], 0, timeout)
  File "/app/scheduler/__init__.py", line 72, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'KubeHTTPClient' object has no attribute '_scale_rc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 503, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 509, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: 'KubeHTTPClient' object has no attribute '_scale_rc'
10.245.52.137 "POST /v2/hooks/build/ HTTP/1.1" 400 65 "deis-builder"```

**Comment by sstarcher** [comment]
@helgi any way to work around this with v2.5 without deleting the app and taking it out of service?

**Comment by helgi** [comment]
I don't think so since it is a scale down operation first and then RC delete. I assume you have a Deployment and an RC now fighting?

When this gets merged you could use a master branch version of the controller image until we release a patch version of Workflow

Alternatively, you could downgrade and convert things to Deployments in place (was highly recommended in the release blog post for 2.3 -> 2.4 I believe) and then move to 2.5

**Comment by sstarcher** [comment]
So it looks like where the error happens both the new deployment and the rc exist.  So when deleting the rc the traffic will go to the pods that were created by the deployment.  Looks like if you gracefully delete the rc it should not cause downtime.

**Comment by helgi** [comment]
Ah yeah - Deployment did get to be the new version and RC is the old. The Service picks all versions to send traffic to.

So the workaround is to delete the RC by hand after the failure and you should be good.
