### ISSUE TITLE
autoscale:set throws an exception

### ISSUE THREAD

**Issue by ineu** [deis/controller#1159]
Deis version: 2.8

```
> $ deis autoscale:set web --min=12 --max=25 --cpu-percent=75
Applying autoscale settings for process type web on test... Error: Unknown Error (400): {"detail":"could not convert string to float: '1.2+'"}
```
Controller's logs contain the following:
```
ERROR:root:could not convert string to float: '1.2+'
Traceback (most recent call last):
  File "/app/api/models/appsettings.py", line 148, in save
    self.update_autoscale(previous_settings)
  File "/app/api/models/appsettings.py", line 119, in update_autoscale
    self.app.autoscale(proc, scale)
  File "/app/api/models/app.py", line 925, in autoscale
    self._scheduler.hpa.get(self.id, name)
  File "/app/scheduler/resources/horizontalpodautoscaler.py", line 33, in get
    url = self.api(url, *args)
  File "/app/scheduler/resources/__resource.py", line 28, in api
    return "/{}/{}".format(self.api_prefix, self.api_version) + tmpl.format(*args)
  File "/app/scheduler/resources/horizontalpodautoscaler.py", line 14, in api_version
    if self.version() >= 1.3:
  File "/app/scheduler/__init__.py", line 83, in version
    return float('{}.{}'.format(data['major'], data['minor']))
ValueError: could not convert string to float: '1.2+'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 181, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 20, in perform_create
    obj = serializer.save(owner=self.request.user)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 879, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/api/models/appsettings.py", line 153, in save
    raise DeisException(str(e)) from e
api.exceptions.DeisException: could not convert string to float: '1.2+'
10.42.0.1 "POST /v2/apps/test/settings/ HTTP/1.1" 400 54 "Deis Client v2.7.1"

```

**Comment by bacongobbler** [comment]
That bug indicates that the version number returned from kubernetes is not what we expect it to be: https://github.com/deis/controller/blob/master/rootfs/scheduler/__init__.py#L76-L83

Can you post the output of `kubectl version`? I think the version parsing logic is flawed and needs to account for semver suffixes.

**Comment by ineu** [comment]
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.4-rancher10", GitCommit:"89cee3343e96f0d40b52ab2d3d6765034144abfa", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}

**Comment by bacongobbler** [comment]
It's interesting that the minor version is "2+". Is this specific to rancher?

Either way it's something [we need to address](https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/api/swagger-spec/version.json#L46-L51), likely with [the semver package instead](https://pypi.python.org/pypi/semver).

**Comment by ineu** [comment]
I don't know if it's specific to Rancher only. But I have another kube cluster with 1.4 (set up manually) and it's as expected:
```
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bacongobbler** [comment]
This is likely again due to using an older version of k8s. I'll re-open the minimum requirements doc to deprecate v1.2 support.

**Comment by ineu** [comment]
I've just set up recent version or rancher and it also has this `+` addition:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9
d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"
}                                                                                                                       
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.6-rancher1", GitCommit:"95f43c93c49cf2b64a1194e010c
1d66325f5b55d", GitTreeState:"clean", BuildDate:"2016-11-15T00:08:34Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"li
nux/amd64"}   
```

**Comment by bacongobbler** [comment]
try #1167
