### ISSUE TITLE
Controller attempts and fails to create resources with invalid name, e.g. starting w/ number

### ISSUE THREAD

**Issue by mhulscher** [deis/controller#1160]
From the Deis CLI:

```
$ deis create 24beers --no-remote
Creating Application... Error: Unknown Error (503): {"detail":"Kubernetes resources could not be created"}

$ deis create 24beers --no-remote
Creating Application... Error: Application with this id already exists.
```

```
Workflow CLI Version:            v2.9.1
Workflow CLI API Version:        2.3
Workflow Controller API Version: 2.3
```

Controller logs (collected w/ stern)
```
deis-controller-224444190-slpx1 deis-controller INFO [24beers]: config 24beers-60798d1 updated
deis-controller-224444190-slpx1 deis-controller INFO [24beers]: mitch.hulscher created initial release
deis-controller-224444190-slpx1 deis-controller ERROR:root:('failed to create Service "24beers" in Namespace "24beers": 422 status code 422 Service "24beers" is invalid: metadata.name: Invalid value: "24beers": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. \'my-name\' or \'abc-123\')', '24beers', '24beers')
deis-controller-224444190-slpx1 deis-controller Traceback (most recent call last):
deis-controller-224444190-slpx1 deis-controller   File "/app/api/models/app.py", line 215, in create
deis-controller-224444190-slpx1 deis-controller     self._scheduler.svc.get(namespace, service)
deis-controller-224444190-slpx1 deis-controller   File "/app/scheduler/resources/service.py", line 26, in get
deis-controller-224444190-slpx1 deis-controller     raise KubeHTTPException(response, message, *args)
deis-controller-224444190-slpx1 deis-controller scheduler.exceptions.KubeHTTPException: ('failed to get Service "24beers" in Namespace "24beers": 404 Not Found services "24beers" not found', '24beers', '24beers')
deis-controller-224444190-slpx1 deis-controller 
deis-controller-224444190-slpx1 deis-controller During handling of the above exception, another exception occurred:
deis-controller-224444190-slpx1 deis-controller 
deis-controller-224444190-slpx1 deis-controller Traceback (most recent call last):
deis-controller-224444190-slpx1 deis-controller   File "/app/api/models/app.py", line 217, in create
deis-controller-224444190-slpx1 deis-controller     self._scheduler.svc.create(namespace, service)
deis-controller-224444190-slpx1 deis-controller   File "/app/scheduler/resources/service.py", line 63, in create
deis-controller-224444190-slpx1 deis-controller     'create Service "{}" in Namespace "{}"', namespace, namespace
deis-controller-224444190-slpx1 deis-controller scheduler.exceptions.KubeHTTPException: ('failed to create Service "24beers" in Namespace "24beers": 422 status code 422 Service "24beers" is invalid: metadata.name: Invalid value: "24beers": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. \'my-name\' or \'abc-123\')', '24beers', '24beers')
deis-controller-224444190-slpx1 deis-controller 
deis-controller-224444190-slpx1 deis-controller The above exception was the direct cause of the following exception:
deis-controller-224444190-slpx1 deis-controller 
deis-controller-224444190-slpx1 deis-controller Traceback (most recent call last):
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 474, in dispatch
deis-controller-224444190-slpx1 deis-controller     response = handler(request, *args, **kwargs)
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
deis-controller-224444190-slpx1 deis-controller     self.perform_create(serializer)
deis-controller-224444190-slpx1 deis-controller   File "/app/api/viewsets.py", line 20, in perform_create
deis-controller-224444190-slpx1 deis-controller     obj = serializer.save(owner=self.request.user)
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 214, in save
deis-controller-224444190-slpx1 deis-controller     self.instance = self.create(validated_data)
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 902, in create
deis-controller-224444190-slpx1 deis-controller     instance = ModelClass.objects.create(**validated_data)
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
deis-controller-224444190-slpx1 deis-controller     return getattr(self.get_queryset(), name)(*args, **kwargs)
deis-controller-224444190-slpx1 deis-controller   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in create
deis-controller-224444190-slpx1 deis-controller     obj.save(force_insert=True, using=self.db)
deis-controller-224444190-slpx1 deis-controller   File "/app/api/models/app.py", line 122, in save
deis-controller-224444190-slpx1 deis-controller     self.create(*args, **kwargs)
deis-controller-224444190-slpx1 deis-controller   File "/app/api/models/app.py", line 226, in create
deis-controller-224444190-slpx1 deis-controller     raise ServiceUnavailable('Kubernetes resources could not be created') from e
deis-controller-224444190-slpx1 deis-controller api.exceptions.ServiceUnavailable: Kubernetes resources could not be created
deis-controller-224444190-slpx1 deis-controller 10.19.112.0 "POST /v2/apps/ HTTP/1.1" 503 54 "Deis Client v2.9.1"
```

The Kubernetes resources are indeed not created, but the app is written to the Deis DB.
Preferably Deis should not attempt to create the app if the name is invalid and be more informative of what failed.

**Comment by bacongobbler** [comment]
thanks for the report. I've fixed this in #1163 which should make it into v2.10.
