### ISSUE TITLE
400 error on `deis pull deis/example-go`

### ISSUE THREAD

**Issue by monaka** [deis/controller#1194]
I deployed Deis Workflow v2.9.1 to AWS (not Azure) for my customer.
Installation was succeeded (maybe ;-) but I got an error like below. 

```
$ deis pull deis/example-go -a example-go
Creating build... Error: Unknown Error (400): {"detail":"PORT needs to be set in the application config when using a private registry"}
```

This error should be fixed in #1136 .

After the error above, I deployed by `git push deis master`.
In this case, deploy was succeeded but it doesn't boot up. Router returns 503.

But the deployment is succeeded and I can access it via http://node-js-getting-started.{my-dais}/ when I use Heroku's repo.

```
$ git clone https://github.com/heroku/node-js-getting-started.git
$ cd node-js-getting-started/
$ deis create node-js-getting-started
$ git push deis master
```

I suspect there have something wrong on the docker image `deis/example-go`.

**Comment by mboersma** [comment]
The `example-go` app works for me on Workflow master:
```shell
$ deis pull deis/example-go -a zydeco-jailbird
Creating build... done
```

@monaka could you post the deis-controller logs related to the `PORT` error? The `deis/example-go` app is indeed routable, and isn't in a private registry, so I'm not sure what's going on here.

**Comment by monaka** [comment]
@mboersma The log is like this.
And I tested to pull `deis/example-go` into my Deis v2.9.1 hosted by Azure. It was deployed with no trouble.
So my first opinion is wrong. 

```
$ kubectl logs --namespace deis deis-controller-1768537734-lramo
100.96.2.11 "GET /v2/apps/?limit=100 HTTP/1.1" 200 1142 "Deis Client v2.9.1-3e324ea"
INFO [example-go]: buildpack type detected. Defaulting to $PORT 5000
INFO [example-go]: buildpack type detected. Defaulting to $PORT 5000
INFO [example-go]: scaling Deployment example-go-web from 1 to 0 replicas
INFO [example-go]: deis-servant scaled pods web=0
INFO [example-go]: build example-go-c1b2e39 created
INFO [example-go]: deis-servant deployed deis/example-go
INFO [example-go]: deis/example-go exists in the target registry. Using image for release 5 of app example-go
ERROR:root:PORT needs to be set in the application config when using a private registry
Traceback (most recent call last):
  File "/app/api/models/release.py", line 159, in get_port
    'PORT needs to be set in the application config '
api.exceptions.DeisException: PORT needs to be set in the application config when using a private registry

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 65, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 468, in deploy
    deploys[scale_type] = self._gather_app_settings(release, app_settings, scale_type, replicas)  # noqa
  File "/app/api/models/app.py", line 1019, in _gather_app_settings
    envs = self._build_env_vars(release)
  File "/app/api/models/app.py", line 830, in _build_env_vars
    port = release.get_port()
  File "/app/api/models/release.py", line 179, in get_port
    raise DeisException(str(e)) from e
api.exceptions.DeisException: PORT needs to be set in the application config when using a private registry

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 185, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 268, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 79, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: PORT needs to be set in the application config when using a private registry
100.96.2.11 "POST /v2/apps/example-go/builds/ HTTP/1.1" 400 89 "Deis Client v2.9.1-3e324ea"
```

**Comment by bacongobbler** [comment]
Can you check the following information to confirm?

```
deis registry:list
kubectl --namespace deis exec deis-controller-1768537734-lramo env | grep DEIS_REGISTRY_LOCATION
deis routing:info
```

In v2.9.1 that error [can only be raised if](https://github.com/deis/controller/blob/v2.9.1/rootfs/api/models/release.py#L154-L161):

a) `deis registry:list` is not empty or the REGISTRY_LOCATION is set to something other than `on-cluster`,
b) a PORT environment variable is not set via `deis config:set`, and
c) the app is routable via `deis routing:info`.

**Comment by monaka** [comment]
Indeed I set up this cluster with ECR. I must set PORT by hand?

```
$ deis registry:list
Error: "No App matches the given query."
$ deis registry:list -a example-go
=== example-go Registry
```

```
$ kubectl --namespace deis exec deis-controller-1768537734-lramo env | grep DEIS_REGISTRY_LOCATION
DEIS_REGISTRY_LOCATION=ecr
```

```
$ deis routing:info -a example-go
Routing is enabled.
```

**Comment by monaka** [comment]
I see this is the specification written at https://deis.com/docs/workflow/applications/using-docker-images/. 
I didn't know it since I'm using on-cluster registry...
@mboersma @bacongobbler Thank you for your helps.

**Comment by bacongobbler** [comment]
If you're set up with ECR, that is an off-cluster registry. :)
