### ISSUE TITLE
build broken/make test failure due to dependencies

### ISSUE THREAD

**Issue by vdice** [deis/controller#1262]
From most recent Travis build: https://travis-ci.org/deis/controller/builds/209529639

```
$ python --version
Python 3.5.2
$ pip --version
pip 8.1.2 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
before_install
0.22s$ createdb -U postgres deis
install.1
41.18s$ pip install -r rootfs/requirements.txt
...
3.58s$ pip install -r rootfs/dev_requirements.txt
16.30s$ make test
cd rootfs && flake8 --show-source
docker run --rm -v /home/travis/build/deis/controller:/workdir -w /workdir quay.io/deis/shell-dev shellcheck rootfs/bin/boot rootfs/bin/reload  _scripts/deploy.sh
Unable to find image 'quay.io/deis/shell-dev:latest' locally
latest: Pulling from deis/shell-dev
Status: Downloaded newer image for quay.io/deis/shell-dev:latest
cd rootfs && python manage.py check
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/deis/controller/rootfs/api/models/__init__.py", line 142, in <module>
    from .certificate import Certificate, validate_certificate  # noqa
  File "/home/travis/build/deis/controller/rootfs/api/models/certificate.py", line 2, in <module>
    from pyasn1.codec.der import decoder as der_decoder
ImportError: No module named 'pyasn1'
make: *** [test-check] Error 1
```

**Comment by vdice** [comment]
🤔 not able to reproduce locally on my box... only slight diff is I'm running pip 8.1.1 instead of 8.1.2 seen on travis
