### ISSUE TITLE
bug(workflow): error during startup because of missing service

### ISSUE THREAD

**Issue by aledbf** [deis/controller#457]
```
Publishing DB state to k8s...
Traceback (most recent call last):
  File "/app/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/api/management/commands/load_db_state_to_k8s.py", line 15, in handle
    obj.save()
  File "/app/api/models/domain.py", line 23, in save
    config = self._load_service_config(app, 'router')
  File "/app/api/models/__init__.py", line 71, in _load_service_config
    svc = self._fetch_service_config(app)
  File "/app/api/models/__init__.py", line 61, in _fetch_service_config
    svc = self._scheduler._get_service(app, app).json()
  File "/app/scheduler/__init__.py", line 1054, in _get_service
    error(response, 'get Service "{}" in Namespace "{}"', name, namespace)
  File "/app/scheduler/__init__.py", line 281, in error
    raise KubeHTTPException(errmsg, response=response)
scheduler.KubeHTTPException: failed to get Service "app-name" in Namespace "app-name": 404 Not Found
{'status': 'Failure', 'metadata': {}, 'message': 'services "app-name" not found', 'reason': 'NotFound', 'kind': 'Status', 'apiVersion': 'v1', 'code': 404, 'details': {'kind': 'services', 'name': 'app-name'}}
```

**Comment by helgi** [comment]
We have the same issue with missing/conflicting Namespace and RC as well.

Did your particular situation happen due to a failed deploy?

**Comment by aledbf** [comment]
@helgi I removed the service just to see if is recreated using scale (I saw the same thing with ns and rc)

**Comment by helgi** [comment]
Ah, that's a known failure scenario. Right now it is all pretty dumb but I have a few things in the works to ease that up with the eventual plan of being able to fill in the blanks.

I'll create a meta ticket to track all the various connected open tickets revolving around this.

**Comment by helgi** [comment]
Talking to @aledbf and he ran the command again with the same result but it looks like the `Domain` model is potentially ran before `App` is ever invoked

**Comment by helgi** [comment]
#482 got merged with the fixed and verified by @aledbf
