### ISSUE TITLE
Timeout pushing image to registry

### ISSUE THREAD

**Issue by aledbf** [deis/controller#489]
It's possible to increase the timeout?

```
ERROR Internal Server Error: /v2/apps/srv-proteccion-pdf/builds/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 463, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 558, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 526, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 486, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 175, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/app/api/views.py", line 152, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 288, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 35, in create
    source_version=source_version)
  File "/app/api/models/release.py", line 60, in new
    release.publish()
  File "/app/api/models/release.py", line 77, in publish
    publish_release(source_image, self.image, deis_registry)
  File "/app/registry/dockerclient.py", line 98, in publish_release
    return client.publish_release(source, target, deis_registry)
  File "/app/registry/dockerclient.py", line 47, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 61, in push
    log_output(stream)
  File "/app/registry/dockerclient.py", line 83, in log_output
    for chunk in stream:
  File "/usr/lib/python3.5/site-packages/docker/client.py", line 217, in _stream_helper
    data = reader.read(1)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 231, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

**Comment by helgi** [comment]
Have you seen this happen again? I'll look at what we can do via the docker-client library

**Comment by Akshaykapoor** [comment]
@helgi i'm still facing this issue with version,

```
deis version
v2.10.0
```

and kubernetes 

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:49:33Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

deployed on aws. The ENV var `DOCKER_CLIENT_TIMEOUT`, i added this to my Dockerfile but still the same result.

**Comment by bacongobbler** [comment]
Please upgrade to v2.11.0, this was fixed at that release.

**Comment by Kaffa-MY** [comment]
I come across the same problem with deis v2.14.0
