### ISSUE TITLE
deis pull returns 500

### ISSUE THREAD

**Issue by vdice** [deis/controller#545]
Recent [e2e run](https://ci.deis.io/job/workflow-beta1-test-e2e/8/consoleFull#-54244738856cf7a1c60b2623097d52997) against `workflow-beta1-test` encountered the following (intermittent error):
```
------------------------------
16:16:33 Releases with a deployed app 
16:16:33   can deploy the app
16:16:33   /go/src/github.com/deis/workflow-e2e/tests/releases_test.go:64
16:16:35 $ deis login http://deis.10.11.245.125.xip.io --username=test-81 --password=asdf1234
16:16:35 Logged in as test-81
16:16:35 $ git init
16:16:35 Initialized empty Git repository in /tmp/deis-workflow-test298862793/.git/
16:16:35 $ deis apps:create test-358090989 
16:16:36 Creating Application... ...o..done, created test-358090989
16:16:36 Git remote deis added
16:16:36 remote available at ssh://git@deis.10.11.245.125.xip.io:2222/test-358090989.git
16:16:36 $ deis pull deis/example-go -a test-358090989 
16:16:43 Creating build... ...o...o...o...o...o...o...o...o...o...o...o...o...o...o.Error: 
16:16:43 500 Internal Server Error
16:16:43 <h1>Server Error (500)</h1>
16:16:43 
16:16:43 $ rm -rf .git
16:16:43 
16:16:43 • Failure [9.682 seconds]
16:16:43 Releases
16:16:43 /go/src/github.com/deis/workflow-e2e/tests/releases_test.go:66
16:16:43   with a deployed app
16:16:43   /go/src/github.com/deis/workflow-e2e/tests/releases_test.go:65
16:16:43     can deploy the app [It]
16:16:43     /go/src/github.com/deis/workflow-e2e/tests/releases_test.go:64
16:16:43 
16:16:43     No future change is possible.  Bailing out early after 7.247s.
16:16:43     Expected
16:16:43         <int>: 1
16:16:43     to match exit code:
16:16:43         <int>: 0
16:16:43 
16:16:43     /go/src/github.com/deis/workflow-e2e/tests/builds_test.go:32
16:16:43 ------------------------------
```

Associated log artifacts can be found [here](https://ci.deis.io/job/workflow-beta1-test-e2e/8/artifact/logs/8/)

**Comment by helgi** [comment]
Looks like we need to catch Docker exceptions and decide how to output the error

```
ERROR Internal Server Error: /v2/apps/test-358090989/builds/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 175, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/app/api/views.py", line 152, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 288, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 40, in create
    source_version=source_version
  File "/app/api/models/release.py", line 62, in new
    release.publish()
  File "/app/api/models/release.py", line 82, in publish
    publish_release(source_image, self.image, deis_registry)
  File "/app/registry/dockerclient.py", line 98, in publish_release
    return client.publish_release(source, target, deis_registry)
  File "/app/registry/dockerclient.py", line 47, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 61, in push
    log_output(stream)
  File "/app/registry/dockerclient.py", line 87, in log_output
    raise docker.errors.DockerException(chunk)
docker.errors.DockerException: b'{"errorDetail":{"message":"Put http://10.11.240.67:80/v1/repositories/test-358090989/: dial tcp 10.11.240.67:80: connection refused"},"error":"Put http://10.11.240.67:80/v1/repositories/test-358090989/: dial tcp 10.11.240.67:80: connection refused"}\r\n'
```

**Comment by slack** [comment]
Connection refused from registry:
```
ERROR Internal Server Error: /v2/apps/test-358090989/builds/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 175, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/app/api/views.py", line 152, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 288, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 40, in create
    source_version=source_version
  File "/app/api/models/release.py", line 62, in new
    release.publish()
  File "/app/api/models/release.py", line 82, in publish
    publish_release(source_image, self.image, deis_registry)
  File "/app/registry/dockerclient.py", line 98, in publish_release
    return client.publish_release(source, target, deis_registry)
  File "/app/registry/dockerclient.py", line 47, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 61, in push
    log_output(stream)
  File "/app/registry/dockerclient.py", line 87, in log_output
    raise docker.errors.DockerException(chunk)
docker.errors.DockerException: b'{"errorDetail":{"message":"Put http://10.11.240.67:80/v1/repositories/test-358090989/: dial tcp 10.11.240.67:80: connection refused"},"error":"Put http://10.11.240.67:80/v1/repositories/test-358090989/: dial tcp 10.11.240.67:80: connection refused"}\r\n'
```

```
deis-registry           10.11.240.67    <none>          80/TCP                             app=deis-registry           22m
```

**Comment by slack** [comment]
HAI @helgi

**Comment by slack** [comment]
Looks like registry failed liveness probe, sometime during the run:
```
  15m		15m		3	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 503
  15m		15m		1	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Killing		Killing container with docker id 4dd2a9667c45: pod "deis-registry-mv1ex_deis(50e96a5f-efb1-11e5-8fd7-42010af00078)" container "deis-registry" is unhealthy, it will be killed and re-created.
  15m		15m		1	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Created		Created container with docker id 4e46c8fff64d
  15m		15m		1	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Started		Started container with docker id 4e46c8fff64d
  23m		15m		3	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Pulled		Container image "quay.io/deisci/registry:git-d019479" already present on machine
  15m		15m		3	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Unhealthy	Readiness probe failed: HTTP probe failed with statuscode: 503
  14m		14m		1	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Unhealthy	Liveness probe failed: Get http://10.8.0.5:5000/v2/: net/http: request canceled while waiting for connection
  14m		14m		1	{kubelet gke-helm-testing-8923-a1ee2a66-node-cmqa}	spec.containers{deis-registry}	Unhealthy	Readiness probe failed: Get http://10.8.0.5:5000/v2/: net/http: request canceled while waiting for connection
```

**Comment by slack** [comment]
Also looks like minio may have popped, seeing tons of failed writes in the log.

**Comment by helgi** [comment]
So we intentionally raise an exception at https://github.com/deis/controller/blob/master/rootfs/registry/dockerclient.py#L87 but nothing further up the stack handles it

**Comment by slack** [comment]
Getting the feeling that minio popped which caused registry to pop, which caused the tests to pop.

Most look related to liveness check fails... possibly due to timeout.

**Comment by slack** [comment]
Using the other ticket as the feature request.
