### ISSUE TITLE
Controller bailing out while recovering from an existing data

### ISSUE THREAD

**Issue by smothiki** [deis/controller#650]
During first install I created a deis pull app which failed or create any app that failed while doing git push which basically doesn't have a build object but supposed to have one
Cleared kubernetes cluster and reinstalled deis . controller bails out with the following error. 
```
le applications
Traceback (most recent call last):
  File "/app/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/api/management/commands/load_db_state_to_k8s.py", line 28, in handle
    application.deploy(rel)
  File "/app/api/models/app.py", line 335, in deploy
    raise EnvironmentError('No build associated with this release')
OSError: No build associated with this release
```

**Comment by smothiki** [comment]
Also is there a possibility that the recovering happens inside a thread not part of the main process?

**Comment by bacongobbler** [comment]
> Also is there a possibility that the recovering happens inside a thread not part of the main process?

Yes, recovery occurs outside of the server: https://github.com/deis/controller/blob/b5ba78db0d12bca988de1d56f247ef591f387d12/rootfs/bin/boot#L35-L38
