### ISSUE TITLE
Exception when controller verifies application health with router

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#667]
First deployment attempt .  I'm not sure where the 192.168 address is coming from

```
DEBUG No prior RC could be found for kibana-cmd
DEBUG scaling release kibana-v2-cmd to 1 out of final 1
DEBUG Not scaling RC kibana-v2-cmd in Namespace kibana to 1 replicas. Already at desired replicas
DEBUG scaled up pod number 1 for kibana-v2-cmd
DEBUG Failed to find port for Docker image 192.168.3.2:80/kibana:git-0f2ffac5, defaulting to 5000
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.245.112.129 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
ERROR kibana: kibana-v2-cmd (app::deploy): HTTPConnectionPool(host='192.168.3.135', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbc3153d0b8>, 'Connection to 192.168.3.135 timed out. (connect timeout=3)'))
ERROR [kibana]: kibana-v2-cmd (app::deploy): HTTPConnectionPool(host='192.168.3.135', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbc3153d0b8>, 'Connection to 192.168.3.135 timed out. (connect timeout=3)'))
ERROR Internal Server Error: /v2/hooks/build
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbc3153d0b8>, 'Connection to 192.168.3.135 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.3.135', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbc3153d0b8>, 'Connection to 192.168.3.135 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 532, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/app/api/views.py", line 154, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 538, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 44, in create
    self.app.deploy(user, new_release)
  File "/app/api/models/app.py", line 380, in deploy
    self.verify_application_health(**kwargs)
  File "/app/api/models/app.py", line 454, in verify_application_health
    response = session.get(url, timeout=req_timeout)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 432, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.3.135', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbc3153d0b8>, 'Connection to 192.168.3.135 timed out. (connect timeout=3)'))
```

**Comment by helgi** [comment]
You can increase the timeout by setting `DOCKER_CLIENT_TIMEOUT` to a higher value than 30 (default docker client timeout) in the `Controller` RC

**Comment by sstarcher** [comment]
@helgi would that be ```router.deis.io/connectTimeout: "10"```

**Comment by helgi** [comment]
https://github.com/docker/docker-py/blob/master/docker/constants.py#L2 - it's actually 60 seconds

**Comment by helgi** [comment]
@sstarcher No, the Controller does not go via the router to talk to Deis Registry, it uses IPs for that

**Comment by helgi** [comment]
The value is set as an `env` (env var) in the RC: https://github.com/deis/charts/blob/master/workflow-beta2/tpl/deis-controller-rc.yaml#L38

**Comment by sstarcher** [comment]
So I'm setting the following in the controller-rc correct?  On the error I received during the deployment deis-builder said everything was successful and the controller created the pods, but of course no image exists.

```
- name: "DOCKER_CLIENT_TIMEOUT"
value: '360'
```

**Comment by helgi** [comment]
Yeah that should work, make sure to kill the controller pod so it comes up with the new value

**Comment by helgi** [comment]
Oh no, hang on a second... This is a totally different code path, backtraces are hard to read :-|

That IP is the router and we are adding in a little verification on **first** deploy (only) and it is trying to verify that the router has gotten the nginx record for the application for that little 10 second window it may take it to find out about the application. This shouldn't blow up like this, it should be more forgiving and instead just note a failure.

This has nothing to do with the Registry after all :-)

**Comment by helgi** [comment]
@sstarcher I renamed the ticket according my understanding, let me know if you think this caused by something else

**Comment by sstarcher** [comment]
@helgi I believe that is correct
