### ISSUE TITLE
Controller unbound variable response

### ISSUE THREAD

**Issue by sstarcher** [deis/controller#682]
With the latest canary builds as of this post when attempting a ```git push deis```

```
DEBUG create broken
DEBUG create broken
DEBUG deploy broken-v2-cmd, img broken:git-14850e23, params {'version': 'v2', 'cpu': {}, 'memory': {}, 'app_type': 'cmd', 'healthcheck': {}, 'batches': None, 'tags': {}, 'envs': {}, 'replicas': 1, 'build_type': 'dockerfile', 'routable': True}, cmd ""
DEBUG No prior RC could be found for broken-cmd
DEBUG scaling release broken-v2-cmd to 1 out of final 1
DEBUG waiting for 1 pods in broken namespace to be in services (120s timeout)
DEBUG 1 out of 1 pods in namespace broken are in service
ERROR broken: broken-v2-cmd (app::deploy): local variable 'response' referenced before assignment
ERROR [broken]: broken-v2-cmd (app::deploy): local variable 'response' referenced before assignment
DEBUG scaling RC broken-v2-cmd in Namespace broken from 1 to 0 replicas
DEBUG waiting for RC broken-v2-cmd to get a newer resource version than 52587903 (30s timeout)
DEBUG RC broken-v2-cmd has a new resource version 52590288
DEBUG waiting for 1 pods in broken namespace to be terminated (30s timeout)
DEBUG 1 pods in namespace broken are terminated
ERROR Internal Server Error: /v2/hooks/build
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 520, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/app/api/views.py", line 154, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 526, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 44, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 384, in deploy
    self.verify_application_health(**kwargs)
  File "/app/api/models/app.py", line 485, in verify_application_health
    if response.status_code == 404:
UnboundLocalError: local variable 'response' referenced before assignment
10.245.138.151 "POST /v2/hooks/build HTTP/1.1" 500 27 "deis-builder"
```

**Comment by helgi** [comment]
Totally my bad! Fixing, will look at writing tests for this failure scenario
