### ISSUE TITLE
controller cannot deploy if app does not contain a valid image

### ISSUE THREAD

**Issue by bacongobbler** [deis/controller#761]
If you restart the controller when an image does not exist for an application in the registry, the controller fails to boot:

```
Deploying available applications
Traceback (most recent call last):
  File "/app/api/models/release.py", line 171, in get_port
    port = docker_get_port(self.image, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 201, in get_port
    return DockerClient().get_port(target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 78, in get_port
    info = self.inspect_image(target, deis_registry)
  File "/usr/local/lib/python3.5/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.5/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/app/registry/dockerclient.py", line 158, in inspect_image
    self.pull(repo, tag=tag, insecure_registry=insecure_registry)
  File "/app/registry/dockerclient.py", line 129, in pull
    log_output(stream, 'pull', repo, tag)
  File "/app/registry/dockerclient.py", line 179, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 193, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: image go:v3 not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/api/management/commands/load_db_state_to_k8s.py", line 32, in handle
    application.deploy(rel)
  File "/app/api/models/app.py", line 387, in deploy
    envs['PORT'] = release.get_port(routable)
  File "/app/api/models/release.py", line 179, in get_port
    raise DeisException(str(e)) from e
api.exceptions.DeisException: image go:v3 not found
```

I'd expect that the controller would still come up to serve traffic even though the application failed to be deployed.

**Comment by helgi** [comment]
Would we expect people to read the controller logs to see there was a problem? Catching is easy and showing informational messages as well.

My guess is we would have people read the logs if anything is amiss on a recovery. This one they could resolve with a new deploy pointing to a good image

**Comment by bacongobbler** [comment]
Yes in this case I'd expect people to read the controller logs on why their app wasn't deployed on recovery.

**Comment by helgi** [comment]
I agree - only issue is if you have a lot of apps (hard to figure out if any failed) or it just gets lost in the sea of other messages, which can happen if you have a handful of apps.

I have no solution for now to that particular problem :) that's more a "future helgi and matt problem" to ponder on

**Comment by bacongobbler** [comment]
indeed. at some point we can add some form of "doctor" command to diagnose app log issues (or log those errors in the app log so `deis logs` shows application deploy errors), but that's another problem for another day :)
