### ISSUE TITLE
500 on /v2/auth/passwd/, /v2/apps/<id>/run/, and /v2/apps/<id>/domains/ when missing body

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/controller#829]
To reproduce: `POST /v2/auth/passwd/` with a valid token but no body.

Error:
```
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 101, in passwd
    if not target_obj.check_password(request.data['password']):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'password'"
```

**Comment by Joshua-Anderson** [comment]
`/v2/apps/<id>/run/` has the exact same error when missing a body.

**Comment by Joshua-Anderson** [comment]
`POST /v2/apps/<id>/run/` has the same problem, but a different error.

```
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 170, in create
    request.data['app'] = self.get_app()
  File "/usr/local/lib/python3.5/dist-packages/django/http/request.py", line 407, in __setitem__
    self._assert_mutable()
  File "/usr/local/lib/python3.5/dist-packages/django/http/request.py", line 404, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
```

**Comment by Joshua-Anderson** [comment]
I fixed `/v2/auth/passwd/` in #850 and `/v2/apps/<id>/run/` in #952

**Comment by helgi** [comment]
@Joshua-Anderson Can you verify the last one? When I POST an empty body to that domains endpoint I get `{'domain': ['This field is required.']}` back

**Comment by Joshua-Anderson** [comment]
Is looks like it's been fixed, probably by updating DRF or django. Closing!
