### ISSUE TITLE
Error: net/http: transport closed before response was received

### ISSUE THREAD

**Issue by jchauncey** [deis/controller#977]
```
INFO [test-160290737]: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
ERROR:root:Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
Traceback (most recent call last):
  File "/app/api/models/release.py", line 88, in new
    release.publish()
  File "/app/api/models/release.py", line 135, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 196, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 117, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 133, in push
    log_output(stream, 'push', repo, tag)
  File "/app/registry/dockerclient.py", line 175, in log_output
    stream_error(chunk, operation, repo, tag)
  File "/app/registry/dockerclient.py", line 192, in stream_error
    raise RegistryException(message)
registry.dockerclient.RegistryException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 62, in create
    source_version=self.version
  File "/app/api/models/release.py", line 95, in new
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 181, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 258, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: Put http://localhost:5555/v1/repositories/test-160290737/: net/http: transport closed before response was received
10.24.8.6 "POST /v2/apps/test-160290737/builds/ HTTP/1.1" 400 127 "Deis Client vv2.3.0-55247cf"
```

**Comment by helgi** [comment]
That's a configurable timeout value, by default it is the docker py 60 seconds. Increase it if you need more time

**Comment by jchauncey** [comment]
yeah but why are we hitting that bound? what is the cause. If we keep increasing timeouts we are just making the tests run longer

**Comment by helgi** [comment]
The cause is usually one of three

1. massive image
2. [very] slow registry
3. network is crawling

**Comment by jchauncey** [comment]
In this case it can only be `#2` or `#3`

So how can we shield against these types of failures without just jacking up the timeout value

**Comment by helgi** [comment]
We could maybe add retries and hope it picks off where it left off or generally has a better connection.

This assumes that the TTL on the overall connection that initiated a pull/push is longer than 60 seconds
