### ISSUE TITLE
While updating configuration Pods get terminated

### ISSUE THREAD

**Issue by subho007** [deis/controller#980]
I am trying to update the configuration by `deis config:push` it seems while it runs, it ends with 
```
Creating config... Error: Unknown Error (400): {"detail":"(app::deploy): ('failed to failed to create Secret \"sherlock-v4-env\" in Namespace \"sherlock\": 409 Conflict\\n{\\'apiVersion\\': \\'v1\\', \\'kind\\': \\'Status\\', \\'details\\': {\\'name\\': \\'sherlock-v4-env\\', \\'kind\\': \\'secrets\\'}, \\'message\\': \\'secrets \"sherlock-v4-env\" already exists\\', \\'metadata\\': {}, \\'code\\': 409, \\'status\\': \\'Failure\\', \\'reason\\': \\'AlreadyExists\\'}', 'sherlock-v4-env', 'sherlock')"}
```

I checked the logs in deis-controller and I get this traceback:

```
2016-08-12T20:33:11.598319818Z ERROR:root:(app::deploy): ('failed to failed to create Secret "sherlock-v4-env" in Namespace "sherlock": 409 Conflict\n{\'apiVersion\': \'v1\', \'kind\': \'Status\', \'details\': {\'name\': \'sherlock-v4-env\', \'kind\': \'secrets\'}, \'message\': \'secrets "sherlock-v4-env" already exists\', \'metadata\': {}, \'code\': 409, \'status\': \'Failure\', \'reason\': \'AlreadyExists\'}', 'sherlock-v4-env', 'sherlock')
2016-08-12T20:33:11.598367269Z Traceback (most recent call last):
2016-08-12T20:33:11.598375698Z   File "/app/scheduler/__init__.py", line 188, in deploy_rc
2016-08-12T20:33:11.598381207Z     self.get_rc(namespace, name)
2016-08-12T20:33:11.598386362Z   File "/app/scheduler/__init__.py", line 885, in get_rc
2016-08-12T20:33:11.598393839Z     'get ReplicationController "{}" in Namespace "{}"', name, namespace
2016-08-12T20:33:11.598400862Z scheduler.KubeHTTPException: ('failed to get ReplicationController "sherlock-v4-taskscanners" in Namespace "sherlock": 404 Not Found\n{\'apiVersion\': \'v1\', \'kind\': \'Status\', \'details\': {\'name\': \'sherlock-v4-taskscanners\', \'kind\': \'replicationcontrollers\'}, \'message\': \'replicationcontrollers "sherlock-v4-taskscanners" not found\', \'metadata\': {}, \'code\': 404, \'status\': \'Failure\', \'reason\': \'NotFound\'}', 'sherlock-v4-taskscanners', 'sherlock')

2016-08-12T20:33:11.598492259Z Traceback (most recent call last):
2016-08-12T20:33:11.598496661Z   File "/app/api/models/app.py", line 560, in deploy
2016-08-12T20:33:11.598501596Z     async_run(tasks)
2016-08-12T20:33:11.598506173Z   File "/app/api/utils.py", line 161, in async_run
2016-08-12T20:33:11.598510901Z     raise error
2016-08-12T20:33:11.598515102Z   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
2016-08-12T20:33:11.598519475Z     result = self.fn(*self.args, **self.kwargs)
2016-08-12T20:33:11.598523549Z   File "/app/scheduler/__init__.py", line 116, in deploy
2016-08-12T20:33:11.598528224Z     self.deploy_rc(namespace, name, image, entrypoint, command, **kwargs)
2016-08-12T20:33:11.598532429Z   File "/app/scheduler/__init__.py", line 201, in deploy_rc
2016-08-12T20:33:11.598536714Z     **kwargs).json()
2016-08-12T20:33:11.598540687Z   File "/app/scheduler/__init__.py", line 1073, in create_rc
2016-08-12T20:33:11.598545727Z     manifest['spec']['template'] = self._build_pod_manifest(namespace, name, image, **kwargs)
2016-08-12T20:33:11.598552274Z   File "/app/scheduler/__init__.py", line 461, in _build_pod_manifest
2016-08-12T20:33:11.598557093Z     self._set_container(namespace, container_name, container, **kwargs)
2016-08-12T20:33:11.598561984Z   File "/app/scheduler/__init__.py", line 587, in _set_container
2016-08-12T20:33:11.598566364Z     self.set_application_config(namespace, env, kwargs.get('version'))
2016-08-12T20:33:11.598576354Z   File "/app/scheduler/__init__.py", line 562, in set_application_config
2016-08-12T20:33:11.598580654Z     self.create_secret(namespace, secret_name, secrets_env, labels=labels)
2016-08-12T20:33:11.598584875Z   File "/app/scheduler/__init__.py", line 1269, in create_secret
2016-08-12T20:33:11.598589325Z     'failed to create Secret "{}" in Namespace "{}"', name, namespace
2016-08-12T20:33:11.598610369Z scheduler.KubeHTTPException: ('failed to failed to create Secret "sherlock-v4-env" in Namespace "sherlock": 409 Conflict\n{\'apiVersion\': \'v1\', \'kind\': \'Status\', \'details\': {\'name\': \'sherlock-v4-env\', \'kind\': \'secrets\'}, \'message\': \'secrets "sherlock-v4-env" already exists\', \'metadata\': {}, \'code\': 409, \'status\': \'Failure\', \'reason\': \'AlreadyExists\'}', 'sherlock-v4-env', 'sherlock')
2016-08-12T20:33:11.598620382Z 
2016-08-12T20:33:11.598624756Z The above exception was the direct cause of the following exception:
2016-08-12T20:33:11.598630805Z 
2016-08-12T20:33:11.598635295Z Traceback (most recent call last):
2016-08-12T20:33:11.598639610Z   File "/app/api/views.py", line 266, in post_save
2016-08-12T20:33:11.598644278Z     config.app.deploy(self.release)
2016-08-12T20:33:11.598648525Z   File "/app/api/models/app.py", line 564, in deploy
2016-08-12T20:33:11.598659224Z     raise ServiceUnavailable(err) from e
2016-08-12T20:33:11.598677436Z api.exceptions.ServiceUnavailable: (app::deploy): ('failed to failed to create Secret "sherlock-v4-env" in Namespace "sherlock": 409 Conflict\n{\'apiVersion\': \'v1\', \'kind\': \'Status\', \'details\': {\'name\': \'sherlock-v4-env\', \'kind\': \'secrets\'}, \'message\': \'secrets "sherlock-v4-env" already exists\', \'metadata\': {}, \'code\': 409, \'status\': \'Failure\', \'reason\': \'AlreadyExists\'}', 'sherlock-v4-env', 'sherlock')
```

Can someone help me?

Stats:
Kubernetes: 1.3.4
Workflow: v2.3.0
Postgresql hosted off-cluster

**Comment by helgi** [comment]
How many releases do you have if you do `deis releases` for the app

**Comment by subho007** [comment]
I am recreating the cluster once again, I know how to reproduce the issue. Need 10 min

**Comment by subho007** [comment]
@helgi doing a `deis releases` shows me 3 releases

Here is how recreated the problem succesfully:

I have an app with 7 processes in Procfile.

1. Create deis app
2. deis config:push
3. git push deis master
4. deis scale web=1 taskmails=1 taskcelery=1 taskreport=1 taskdevices=1 taskscanners=2 taskdownloads=1
5. Change `.env`
6. deis config:push
7. Mayhem: 
```
❯❯❯ deis config:push
Creating config... Error: Unknown Error (400): {"detail":"(app::deploy): ('failed to failed to create Secret \"sherlock-v4-env\" in Namespace \"sherlock\": 409 Conflict\\n{\\'apiVersion\\': \\'v1\\', \\'kind\\': \\'Status\\', \\'details\\': {\\'name\\': \\'sherlock-v4-env\\', \\'kind\\': \\'secrets\\'}, \\'message\\': \\'secrets \"sherlock-v4-env\" already exists\\', \\'metadata\\': {}, \\'code\\': 409, \\'status\\': \\'Failure\\', \\'reason\\': \\'AlreadyExists\\'}', 'sherlock-v4-env', 'sherlock')"}
```

**Comment by bacongobbler** [comment]
@subho007 can you try with a completely different app name? Just want to rule out the fact that `sherlock-v4-env` was not there in the `sherlock` namespace before this all began. The error in particular is

> secrets "sherlock-v4-env" already exists

**Comment by subho007** [comment]
@bacongobbler on it, takes a while to build it

**Comment by subho007** [comment]
@bacongobbler this time a different error:

```
❯❯❯ deis config:push
Creating config... Error: Post http://deis.appknox.com/v2/apps/appknox/config/: EOF
```

A `deis config:list` shows that it was updated.

`deis releases` shows 3 releases

**Comment by subho007** [comment]
I guess you can close this, because this works properly. But just be sure, I wanted to check if I do a `deis apps:destroy` does it actually delete references properly or not

**Comment by subho007** [comment]
@bacongobbler I again got this error cropped up :(

```
2016-08-14T19:07:40.754177202Z ERROR [sherlock]: (app::deploy): ('failed to failed to create Secret "sherlock-v12-env" in Namespace "sherlock": 409 Conflict\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" already exists\', \'code\': 409, \'reason\': \'AlreadyExists\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:40.795090373Z INFO [sherlock]: scaling RC sherlock-v12-taskdevices from 1 to 0 replicas
2016-08-14T19:07:41.837570731Z INFO [sherlock]: waiting for 1 pods to be terminated (30s timeout)
2016-08-14T19:07:44.879272092Z INFO [sherlock]: 1 pods are terminated
2016-08-14T19:07:44.904728515Z INFO [sherlock]: scaling RC sherlock-v12-taskdownloads from 1 to 0 replicas
2016-08-14T19:07:45.942758448Z INFO [sherlock]: waiting for 1 pods to be terminated (30s timeout)
2016-08-14T19:07:47.969914781Z INFO [sherlock]: 1 pods are terminated
2016-08-14T19:07:47.997734721Z INFO [sherlock]: scaling RC sherlock-v12-taskscanners from 2 to 0 replicas
2016-08-14T19:07:49.035555627Z INFO [sherlock]: waiting for 2 pods to be terminated (30s timeout)
2016-08-14T19:07:52.084927781Z INFO [sherlock]: 2 pods are terminated
2016-08-14T19:07:52.121667617Z INFO [sherlock]: scaling RC sherlock-v12-web from 1 to 0 replicas
2016-08-14T19:07:53.176898481Z INFO [sherlock]: waiting for 1 pods to be terminated (30s timeout)
2016-08-14T19:07:55.203587395Z INFO [sherlock]: 1 pods are terminated
2016-08-14T19:07:55.237393694Z ERROR:root:(app::deploy): ('failed to failed to create Secret "sherlock-v12-env" in Namespace "sherlock": 409 Conflict\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" already exists\', \'code\': 409, \'reason\': \'AlreadyExists\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:55.237437687Z Traceback (most recent call last):
2016-08-14T19:07:55.237445724Z   File "/app/scheduler/__init__.py", line 188, in deploy_rc
2016-08-14T19:07:55.237453525Z     self.get_rc(namespace, name)
2016-08-14T19:07:55.237461203Z   File "/app/scheduler/__init__.py", line 885, in get_rc
2016-08-14T19:07:55.237468794Z     'get ReplicationController "{}" in Namespace "{}"', name, namespace
2016-08-14T19:07:55.237481566Z scheduler.KubeHTTPException: ('failed to get ReplicationController "sherlock-v12-taskcelery" in Namespace "sherlock": 404 Not Found\n{\'details\': {\'name\': \'sherlock-v12-taskcelery\', \'kind\': \'replicationcontrollers\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'replicationcontrollers "sherlock-v12-taskcelery" not found\', \'code\': 404, \'reason\': \'NotFound\'}', 'sherlock-v12-taskcelery', 'sherlock')
2016-08-14T19:07:55.237495211Z 
2016-08-14T19:07:55.237501924Z During handling of the above exception, another exception occurred:
2016-08-14T19:07:55.237508769Z 
2016-08-14T19:07:55.237515627Z Traceback (most recent call last):
2016-08-14T19:07:55.237522719Z   File "/app/scheduler/__init__.py", line 560, in set_application_config
2016-08-14T19:07:55.237530709Z     self.get_secret(namespace, secret_name)
2016-08-14T19:07:55.237538557Z   File "/app/scheduler/__init__.py", line 1206, in get_secret
2016-08-14T19:07:55.237546368Z     'get Secret "{}" in Namespace "{}"', name, namespace
2016-08-14T19:07:55.237554936Z scheduler.KubeHTTPException: ('failed to get Secret "sherlock-v12-env" in Namespace "sherlock": 404 Not Found\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" not found\', \'code\': 404, \'reason\': \'NotFound\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:55.237567221Z 
2016-08-14T19:07:55.237574651Z During handling of the above exception, another exception occurred:
2016-08-14T19:07:55.237596633Z 
2016-08-14T19:07:55.237603242Z Traceback (most recent call last):
2016-08-14T19:07:55.237609256Z   File "/app/api/models/app.py", line 560, in deploy
2016-08-14T19:07:55.237615371Z     async_run(tasks)
2016-08-14T19:07:55.237621337Z   File "/app/api/utils.py", line 161, in async_run
2016-08-14T19:07:55.237627863Z     raise error
2016-08-14T19:07:55.237635077Z   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
2016-08-14T19:07:55.237642023Z     result = self.fn(*self.args, **self.kwargs)
2016-08-14T19:07:55.237649457Z   File "/app/scheduler/__init__.py", line 116, in deploy
2016-08-14T19:07:55.237656664Z     self.deploy_rc(namespace, name, image, entrypoint, command, **kwargs)
2016-08-14T19:07:55.237663642Z   File "/app/scheduler/__init__.py", line 201, in deploy_rc
2016-08-14T19:07:55.237670892Z     **kwargs).json()
2016-08-14T19:07:55.237677406Z   File "/app/scheduler/__init__.py", line 1073, in create_rc
2016-08-14T19:07:55.237685740Z     manifest['spec']['template'] = self._build_pod_manifest(namespace, name, image, **kwargs)
2016-08-14T19:07:55.237696456Z   File "/app/scheduler/__init__.py", line 461, in _build_pod_manifest
2016-08-14T19:07:55.237705154Z     self._set_container(namespace, container_name, container, **kwargs)
2016-08-14T19:07:55.237712363Z   File "/app/scheduler/__init__.py", line 587, in _set_container
2016-08-14T19:07:55.237719917Z     self.set_application_config(namespace, env, kwargs.get('version'))
2016-08-14T19:07:55.237727313Z   File "/app/scheduler/__init__.py", line 562, in set_application_config
2016-08-14T19:07:55.237734696Z     self.create_secret(namespace, secret_name, secrets_env, labels=labels)
2016-08-14T19:07:55.237741803Z   File "/app/scheduler/__init__.py", line 1269, in create_secret
2016-08-14T19:07:55.237748994Z     'failed to create Secret "{}" in Namespace "{}"', name, namespace
2016-08-14T19:07:55.237755801Z scheduler.KubeHTTPException: ('failed to failed to create Secret "sherlock-v12-env" in Namespace "sherlock": 409 Conflict\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" already exists\', \'code\': 409, \'reason\': \'AlreadyExists\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:55.237768034Z 
2016-08-14T19:07:55.237775352Z The above exception was the direct cause of the following exception:
2016-08-14T19:07:55.237782525Z 
2016-08-14T19:07:55.237789038Z Traceback (most recent call last):
2016-08-14T19:07:55.237796167Z   File "/app/api/views.py", line 266, in post_save
2016-08-14T19:07:55.237803573Z     config.app.deploy(self.release)
2016-08-14T19:07:55.237810438Z   File "/app/api/models/app.py", line 564, in deploy
2016-08-14T19:07:55.237826196Z     raise ServiceUnavailable(err) from e
2016-08-14T19:07:55.237838633Z api.exceptions.ServiceUnavailable: (app::deploy): ('failed to failed to create Secret "sherlock-v12-env" in Namespace "sherlock": 409 Conflict\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" already exists\', \'code\': 409, \'reason\': \'AlreadyExists\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:55.237849804Z 
2016-08-14T19:07:55.237855503Z The above exception was the direct cause of the following exception:
2016-08-14T19:07:55.237861510Z 
2016-08-14T19:07:55.237867433Z Traceback (most recent call last):
2016-08-14T19:07:55.237873364Z   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
2016-08-14T19:07:55.237880423Z     response = handler(request, *args, **kwargs)
2016-08-14T19:07:55.237887221Z   File "/app/api/views.py", line 176, in create
2016-08-14T19:07:55.237894349Z     return super(AppResourceViewSet, self).create(request, **kwargs)
2016-08-14T19:07:55.237901219Z   File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
2016-08-14T19:07:55.237908558Z     self.perform_create(serializer)
2016-08-14T19:07:55.237914620Z   File "/app/api/viewsets.py", line 21, in perform_create
2016-08-14T19:07:55.237929033Z     self.post_save(obj)
2016-08-14T19:07:55.237935369Z   File "/app/api/views.py", line 269, in post_save
2016-08-14T19:07:55.237941503Z     raise DeisException(str(e)) from e
2016-08-14T19:07:55.237947873Z api.exceptions.DeisException: (app::deploy): ('failed to failed to create Secret "sherlock-v12-env" in Namespace "sherlock": 409 Conflict\n{\'details\': {\'name\': \'sherlock-v12-env\', \'kind\': \'secrets\'}, \'status\': \'Failure\', \'apiVersion\': \'v1\', \'kind\': \'Status\', \'metadata\': {}, \'message\': \'secrets "sherlock-v12-env" already exists\', \'code\': 409, \'reason\': \'AlreadyExists\'}', 'sherlock-v12-env', 'sherlock')
2016-08-14T19:07:55.238449709Z 10.0.0.9 "POST /v2/apps/sherlock/config/ HTTP/1.1" 400 462 "Deis Client v2.3.0"
2016-08-14T19:08:31.303160237Z 10.0.2.6 "GET /v2/hooks/key/d8:e4:53:9e:66:b6:30:59:95:84:ea:34:2d:57:37:4d HTTP/1.1" 200 53 "deis-builder"
2016-08-14T19:08:32.659341013Z 10.0.2.6 "POST /v2/hooks/push HTTP/1.1" 201 377 "deis-builder"
2016-08-14T19:08:32.677945801Z 10.0.2.6 "POST /v2/hooks/config HTTP/1.1" 200 2710 "deis-builder"
```

**Comment by helgi** [comment]
Try switching to Deployments and seeing if that helps. They will be the only option in the next release.

You do it by setting DEIS_KUBERNETES_DEPLOYMENTS=1 with config:set

**Comment by subho007** [comment]
@helgi although it got little stable, but what happens is sometime it fails while I do `git push deis master` with git push failed:

```
       Procfile declares types -> web, workers
-----> Compiled slug size is 156M
Build complete.
Launching App...
remote: 2016/08/14 20:50:22 Error running git receive hook [publishing release (Unexpected error occurred: (app::deploy): There was a problem while deploying v4 of sherlock-web. Going back to the previous release)]
To ssh://git@deis-builder.masked-ip.nip.io:2222/sherlock.git
 ! [remote rejected] bug-fix -> bug-fix (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.masked-ip.nip.io:2222/sherlock.git'
```

And then doing a `deis releases` shows me till v3 but kubernetes tells me otherwise:

<img width="844" alt="screen shot 2016-08-15 at 4 56 26 am" src="https://cloud.githubusercontent.com/assets/81071/17651991/b7719a66-62a4-11e6-9f34-5c21b1da9048.png">




It seems both v3 and v4 exists. I have deleted the app and recreated multiple times now

**Comment by helgi** [comment]
I believe you are being bit by https://github.com/deis/controller/pull/946 - This fix is in master and will be in the release going out this week.

**Comment by subho007** [comment]
@helgi ah yes you are right 👍
