### ISSUE TITLE
500 deleting applications

### ISSUE THREAD

**Issue by slack** [deis/controller#998]
Workflow 2.4.1

```
w:nitro k:nitro ~ $ deis-2.4.0 create --no-remote
Creating Application... done, created yeasty-waxworks
If you want to add a git remote for this app later, use `deis git:remote -a yeasty-waxworks`
w:nitro k:nitro ~ $ deis-2.4.0 destroy -a yeasty-waxworks
 !    WARNING: Potentially Destructive Action
 !    This command will destroy the application: yeasty-waxworks
 !    To proceed, type "yeasty-waxworks" or re-run this command with --confirm=yeasty-waxworks

> yeasty-waxworks
Destroying yeasty-waxworks...
Error: Internal Server Error
w:nitro k:nitro ~ $
```

Controller logs:
```
INFO [yeasty-waxworks]: config yeasty-waxworks-b35bf43 updated
INFO [yeasty-waxworks]: jhansen created initial release
INFO [yeasty-waxworks]: application settings yeasty-waxworks-8f83dad updated
INFO [yeasty-waxworks]: domain yeasty-waxworks added
10.2.92.6 "POST /v2/apps/ HTTP/1.1" 201 169 "Deis Client vv2.4.0"
INFO [yeasty-waxworks]: deleting environment
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "api_push" does not exist
LINE 1: DELETE FROM "api_push" WHERE "api_push"."app_id" IN ('a151ed...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 87, in destroy
    self.perform_destroy(instance)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 91, in perform_destroy
    instance.delete()
  File "/app/api/models/app.py", line 249, in delete
    return super(App, self).delete(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 870, in delete
    return collector.delete()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/deletion.py", line 292, in delete
    count = qs._raw_delete(using=self.using)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 614, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/subqueries.py", line 81, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "api_push" does not exist
LINE 1: DELETE FROM "api_push" WHERE "api_push"."app_id" IN ('a151ed...
                    ^

10.2.92.6 "DELETE /v2/apps/yeasty-waxworks/ HTTP/1.1" 500 25 "Deis Client vv2.4.0"
```

**Comment by helgi** [comment]
Does the same happen if you do it to an app created under 2.4.1? Was the app you create pre-2.4.1?

**Comment by slack** [comment]
App was created and deleted with 2.4.1. On that cluster the database was migrated from a 2.X release up to 2.4.1.

**Comment by helgi** [comment]
Can you run a pg describe on the app table?

**Comment by slack** [comment]
AWS ate this one, if I get some time I'll spin up a new cluster and see if I can reproduce.

**Comment by helgi** [comment]
Have you seen it happen again?

**Comment by slack** [comment]
Nerp, will close.
