### ISSUE TITLE
`git push` throwing error when controller tries to modify annotations

### ISSUE THREAD

**Issue by slack** [deis/controller#999]
```
$ g push deis master -f
Counting objects: 1, done.
Writing objects: 100% (1/1), 267 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 1 (delta 0)
Starting build... but first, coffee!
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from http://rubygems.org/..........
       Fetching version metadata from http://rubygems.org/..
       Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
       Installing rack 1.6.1
       Installing tilt 2.0.1
       Using bundler 1.11.2
       Installing rack-protection 1.5.3
       Installing sinatra 1.4.6
       Bundle complete! 1 Gemfile dependency, 5 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (2.15s)
       Cleaning up the bundler cache.

-----> Discovering process types
       Procfile declares types -> web
       Default process types for Ruby -> rake, console, web
-----> Compiled slug size is 16M
Build complete.
Launching App...
...
...
...
remote: 2016/08/21 05:15:47 Error running git receive hook [publishing release (Unknown Error (400): {"detail":"(app::deploy): 'annotations'"})]
To ssh://git@deis-builder.nitro.deis-demo.works:2222/ribbed-pachinko.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.nitro.deis-demo.works:2222/ribbed-pachinko.git'
```

```
INFO [ribbed-pachinko]: build ribbed-pachinko-a67ef61 created
INFO:api.models.app:[ribbed-pachinko]: build ribbed-pachinko-a67ef61 created
INFO [ribbed-pachinko]: jhansen deployed e159088
INFO:api.models.app:[ribbed-pachinko]: jhansen deployed e159088
INFO [ribbed-pachinko]: buildpack type detected. Defaulting to $PORT 5000
INFO:api.models.app:[ribbed-pachinko]: buildpack type detected. Defaulting to $PORT 5000
INFO [ribbed-pachinko]: adding 30s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
INFO:scheduler:[ribbed-pachinko]: adding 30s on to the original 120s timeout to account for the initial delay specified in the liveness / readiness probe
INFO [ribbed-pachinko]: This deployments overall timeout is 150s - batch timout is 150s and there are 1 batches to deploy with a total of 1 pods
INFO:scheduler:[ribbed-pachinko]: This deployments overall timeout is 150s - batch timout is 150s and there are 1 batches to deploy with a total of 1 pods
INFO [ribbed-pachinko]: waited 10s and 1 pods are in service
INFO:scheduler:[ribbed-pachinko]: waited 10s and 1 pods are in service
INFO [ribbed-pachinko]: waited 20s and 1 pods are in service
INFO:scheduler:[ribbed-pachinko]: waited 20s and 1 pods are in service
INFO [ribbed-pachinko]: waited 30s and 1 pods are in service
INFO:scheduler:[ribbed-pachinko]: waited 30s and 1 pods are in service
ERROR [ribbed-pachinko]: (app::deploy): 'annotations'
ERROR:api.models.app:[ribbed-pachinko]: (app::deploy): 'annotations'
ERROR:root:(app::deploy): 'annotations'
Traceback (most recent call last):
  File "/app/scheduler/__init__.py", line 198, in _update_application_service
    service['metadata']['annotations']['router.deis.io/%s' % key] = str(value)
KeyError: 'annotations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/app.py", line 562, in deploy
    async_run(tasks)
  File "/app/api/utils.py", line 169, in async_run
    raise error
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/app/api/utils.py", line 182, in async_task
    yield from loop.run_in_executor(None, params)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/scheduler/__init__.py", line 148, in deploy
    self._update_application_service(namespace, name, app_type, port, routable, service_annotations)  # noqa
  File "/app/scheduler/__init__.py", line 220, in _update_application_service
    raise KubeException(str(e)) from e
scheduler.KubeException: 'annotations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 566, in deploy
    raise ServiceUnavailable(err) from e
api.exceptions.ServiceUnavailable: (app::deploy): 'annotations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 486, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 492, in post_save
    build.create(self.user)
  File "/app/api/models/build.py", line 71, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: (app::deploy): 'annotations'
10.2.87.4 "POST /v2/hooks/build/ HTTP/1.1" 400 41 "deis-builder"
w:carbon k:nitro example-ruby-sinatra [master]$
```

```
w:carbon k:nitro example-ruby-sinatra [master]$ k --namespace=ribbed-pachinko get svc,deployments,rs,po
NAME                                   CLUSTER-IP   EXTERNAL-IP   PORT(S)      AGE
ribbed-pachinko                        10.3.0.168   <none>        80/TCP       8m
NAME                                   DESIRED      CURRENT       UP-TO-DATE   AVAILABLE   AGE
ribbed-pachinko-web                    1            1             1            1           8m
NAME                                   DESIRED      CURRENT       AGE
ribbed-pachinko-web-1330408578         0            0             8m
ribbed-pachinko-web-2883480714         1            1             2m
NAME                                   READY        STATUS        RESTARTS   AGE
ribbed-pachinko-web-2883480714-4obn5   1/1          Running       0          2m
w:carbon k:nitro example-ruby-sinatra [master]$ k --namespace=ribbed-pachinko describe svc ribbed-pachinko
Name:			ribbed-pachinko
Namespace:		ribbed-pachinko
Labels:			app=ribbed-pachinko,heritage=deis
Selector:		app=ribbed-pachinko,heritage=deis
Type:			ClusterIP
IP:			10.3.0.168
Port:			http	80/TCP
Endpoints:		10.2.47.9:5000
Session Affinity:	None
No events.
```

**Comment by kmala** [comment]
did the app get created with the previous release of controller 2.3.0 and then the controller got upgraded to 2.4.0

**Comment by helgi** [comment]
That scheduler function lacks some key checking or could use `update` or `merge` functionalities to get past this. Tho in somewhat newer (couldn't tell you off the top of my head which tho) versions the Annotation is added even if it is empty, however k8s may to retain that in the output back to us.

The main model (used by a few things) has a few functions that were taking care of the service annotations and such as it was not always going to be around. Basically the same logic is needed in the Scheduler if we want to do this

https://github.com/deis/controller/blob/master/rootfs/api/models/__init__.py#L52-L98
